### ISSUE TITLE
`submitOnChange` is leading to duplicate submissions

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-form#36]
@chawes13 is there a branch where I can test this?

**Comment by chawes13** [comment]
https://github.com/LaunchPadLab/streamlined-checkout-client/tree/refactoring-cart

@dpikt let me know when you are free and I'll walk you through how to set up the test scenario on your local. It seems to be caused when using multiple form components with the same name and is currently reproducible on the Select Add Ons step.

**Comment by dpikt** [comment]
This is an issue with redux-form, tracked here: https://github.com/erikras/redux-form/issues/4222
