### ISSUE TITLE
Allow thrown object to populate SubmissionError messages

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-form#39]
Right now, you can only pass custom messages if you put them under an `errors` key (it's built that way because it matches lp-request's `HTTPError`). However, we could have it fallback to the full object if that key is not present.

Relevant line: https://github.com/LaunchPadLab/lp-form/blob/master/src/middleware/wrapSubmissionErrors.js#L15

cc @chawes13

**Comment by chawes13** [comment]
Even if it is present, I think it's useful to retain information about the originating error
