### ISSUE TITLE
onSubmit should always return a promise

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-form#44]
Redux Form does not coerce `onSubmit` to return a promise. We should wrap it in lp-form. While this isn't a common issue since most of our submit actions are asynchronous, this will solve use cases where we might want to break out of the submission early if certain conditions aren't met. Instead of having to return `Promise.resolve()`, we can simply return and still allow subsequent logic to chain off of the returned promise

**Comment by dpikt** [comment]
Hmm, I think `redux-form` updated to allow sync submits at some point. Can you track that down? The ideal solution might be to upgrade the version of redux-form rather than band-aiding it here.

**Comment by chawes13** [comment]
It allows async submits, but you have to explicitly specify that. Just a thought to reduce bugs.

By default, `redux-form` itself does not wrap it in an async function (see here: https://codesandbox.io/embed/4jwnjq47z0)

**Comment by dpikt** [comment]
Interesting... I think I might've confused it with the default submit function behavior. Sounds good!
